### PR TITLE
Custom command

### PR DESCRIPTION
**Pull request by mgutekunst**
Hi, 

I created a command which is currently located in Tools (can be changed probably) that triggers AceJump. This way the keybinding can be customized using Options->keyboard. 

Removed default keybinding.

### CODE REVIEW

**Comment by mgutekunst** [comment]
If you want to test it using the debugger you need to follow this instructions. http://stackoverflow.com/questions/17625752/cannot-run-vspackage-when-developing-on-multiple-machines/17638350#17638350

To summarize: You need to extend the debugging and start an external program. This setting is saved in the .csproj.user which isn't pushed to the repo.

**Comment by jsturtevant** [comment]
Thanks for working on this!  I will review soon.  Really excited to have this feature as it is the most requested :-)  

Will want to  make sure it works with older version of Visual Studio so might need to make some tweaks as it looks like it is only built for VS 2015 right now.

**Comment by jsturtevant** [comment]
@mgutekunst Sorry it took so long to get around to reviewing.  

This looks good but is missing the tests.  It looks like you re-enabled the tests on your Fork.  Could you include those changes on this PR?

**Comment by mgutekunst** [comment]
No problem, I used the vsix from my branch VsVim-Workaround ;) 

I just updated the branch. Unit tests should be included now.

**Comment by jsturtevant** [comment]
@mgutekunst just released this update in the official package.  Thanks for your help!

**Comment by mgutekunst** [comment]
You're welcome. Thanks for listing me as a contributor in the readme

**Pull request merged**
