### PR TITLE
add Visual Studio 2012 support

### PR DESCRIPTION
**Pull request by aerworker**
I've made the extension to compile and run under Visual Studio 2012

### CODE REVIEW

**Comment by jsturtevant** [comment]
Hi, I tried this change request and when I opened the VS solution in 2013, I was asked to upgrade the project file. This then overwrote some of the changes you made.  When I tried installing it on my VS 2012 instance it installed fine but did not work.  I also tried opening the solution under VS 2012 and got an error that the solution file was not supported.  

This is my first time trying to create VS extension and make it support 2012 is there something I am missing?

**Comment by aerworker** [comment]
Most probably VS 2012 failed to open the solution because of VS SDK is not installed for that version of VS.
It seems that by default VS 2013 doesn't allow to use project made in VS 2012. I've changed MinimumVisualStudioVersion in project, and now it always points to the current VS version. This change eliminate the request for upgrade.
The extension doesn't work in VS 2012 because references to VS assemblies are not version specific. After compilation they are pointed to VS 2013 assemblies. So I've changed references to VS 2012 assemblies.
Now to compile project in the VS 2013 it is required that VS 2012 is installed on the same machine or the following set of assemblies of VS 2012 is accessible through the reference paths.
Microsoft.VisualStudio.CoreUtility.dll
Microsoft.VisualStudio.Text.Data.dll
Microsoft.VisualStudio.Text.Logic.dll
Microsoft.VisualStudio.Text.UI.dll
Microsoft.VisualStudio.Text.UI.Wpf.dll
Although the straightforward way is to use VS 2012 version to develop extensions for later versions of VS.

**Comment by mikehaas763** [comment]
+1

**Comment by jsturtevant** [comment]
Got it committed and released.  Thanks for your help and sorry it took so long.

**Pull request merged**
